apiVersion: web.servers.org/v1alpha1
kind: JBossWebServer
metadata:
  name: example-jbosswebserver
spec:
  # Add fields here
  applicationImage: "registry.redhat.io/jboss-webserver-5/webserver53-openjdk8-tomcat9-openshift-rhel7:latest"
  applicationName: jws-app
  githubWebhookSecret: tomcat
  genericWebhookSecret: tomcat
  mavenMirrorUrl: ""
  artifactDir: ""
  replicas: 2
