apiVersion: web.servers.org/v1alpha1
kind: JBossWebServer
metadata:
  name: example-jbosswebserver
spec:
  # Add fields here
  applicationName: jws-app
  sourceRepositoryUrl: https://github.com/jboss-openshift/openshift-quickstarts.git
  sourceRepositoryRef: "1.2"
  contextDir: tomcat-websocket-chat
  jwsAdminUsername: tomcat
  jwsAdminPassword: tomcat
  githubWebhookSecret: tomcat
  genericWebhookSecret: tomcat
  imageStreamNamespace: openshift
  imageStreamName: jboss-webserver54-openjdk8-tomcat9-ubi8-openshift:latest
  hostnameHttp: ""
  mavenMirrorUrl: ""
  artifactDir: ""
  replicas: 2
