apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jwsservers.web.servers.org
spec:
  group: web.servers.org
  names:
    kind: JBossWebServer
    listKind: JBossWebServerList
    plural: jwsservers
    singular: jwsserver
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description:
            "APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources"
          type: string
        kind:
          description:
            "Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds"
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationImage:
              description: ApplicationImage is the name of the application image
                to be deployed
              type: string
            applicationName:
              type: string
            artifactDir:
              type: string
            contextDir:
              type: string
            genericWebhookSecret:
              type: string
            githubWebhookSecret:
              type: string
            imageStreamNamespace:
              type: string
            imageStreamName:
              type: string
            jwsAdminPassword:
              type: string
            jwsAdminUsername:
              type: string
            serverReadinessScript:
              type: string
            serverLivenessScript:
              type: string
            mavenMirrorUrl:
              type: string
            replicas:
              description: The desired number of replicas for the application
              format: int32
              type: integer
              minimum: 0
            sourceRepositoryRef:
              type: string
            sourceRepositoryUrl:
              type: string
          required:
            - applicationName
            - replicas
          type: object
        status:
          description: JBossWebServerStatus defines the observed state of JBossWebServer
          properties:
            hosts:
              items:
                type: string
              type: array
              x-kubernetes-list-type: set
            pods:
              items:
                description: PodStatus defines the observed state of pods running
                  the JBossWebServer application
                properties:
                  name:
                    type: string
                  podIP:
                    type: string
                  state:
                    description: Represent the state of the Pod, it is used especially
                      during scale down.
                    enum:
                    - ACTIVE
                    - SCALING_DOWN_RECOVERY_INVESTIGATION
                    - SCALING_DOWN_RECOVERY_DIRTY
                    - SCALING_DOWN_CLEAN
                    type: string
                required:
                - name
                - podIP
                - state
                type: object
              type: array
              x-kubernetes-list-type: atomic
            replicas:
              description: Replicas is the actual number of replicas for the application
              format: int32
              type: integer
            scalingdownPods:
              description: "Represents the number of pods which are in scaledown process
                what particular pod is scaling down can be verified by PodStatus \n
                Read-only."
              format: int32
              type: integer
          required:
          - replicas
          - scalingdownPods
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
