apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jwsservers.web.servers.org
spec:
  group: web.servers.org
  names:
    kind: JBossWebServer
    listKind: JBossWebServerList
    plural: jwsservers
    singular: jwsserver
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationName:
              type: string
            artifactDir:
              type: string
            contextDir:
              type: string
            genericWebhookSecret:
              type: string
            githubWebhookSecret:
              type: string
            hostnameHttp:
              type: string
            imageStreamNamespace:
              type: string
            imageStreamName:
              type: string
            jwsAdminPassword:
              type: string
            jwsAdminUsername:
              type: string
            mavenMirrorUrl:
              type: string
            replicas:
              format: int32
              type: integer
            sourceRepositoryRef:
              type: string
            sourceRepositoryUrl:
              type: string
          required:
          - applicationName
          - replicas
          - hostnameHttp
          - sourceRepositoryUrl
          - sourceRepositoryRef
          - contextDir
          - jwsAdminUsername
          - jwsAdminPassword
          - githubWebhookSecret
          - genericWebhookSecret
          - imageStreamNamespace
          - imageStreamName
          - mavenMirrorUrl
          - artifactDir
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
