name: Basic Tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
    
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24
        
    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.14.0
      with:
        minikube version: v1.35.0
        kubernetes version: v1.32.0
        driver: docker

    - name: Setup KUBEBUILDER_ASSETS
      run: |
        export K8S_VERSION=1.20.2
        curl -sSLo envtest-bins.tar.gz "https://go.kubebuilder.io/test-tools/${K8S_VERSION}/$(go env GOOS)/$(go env GOARCH)"
        sudo mkdir /usr/local/kubebuilder
        sudo tar -C /usr/local/kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz
        sudo cp /usr/local/kubebuilder/bin/* /usr/local/bin
       
    - name: Make controller-gen
      run: make controller-gen
      
    - name: Set up vendor
      run: go mod vendor
      
    - name: Basic Operator's Tests
      run: KUBEBUILDER_ASSETS=/usr/local/bin go test -timeout 60m ./... -coverprofile cover.out
